### ISSUE TITLE
Git error 128 arrives while getting dependencies

### ISSUE THREAD

**Issue by Ilyushya** [Hexer10/youtube_downloader_flutter#17]
### Log:
```sh
Git error. Command: `git clone --mirror git://github.com/google/flutter-desktop-embedding.git C:\Users\Ilyushya\AppData\Local\Pub\Cache\git\cache\flutter-desktop-embedding-87b62662532896a522efe2d4fc10c086d1a2768b`
stdout: 
stderr: Cloning into bare repository 'C:\Users\Ilyushya\AppData\Local\Pub\Cache\git\cache\flutter-desktop-embedding-87b62662532896a522efe2d4fc10c086d1a2768b'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Unknown error

exit code: 128
```

**Comment by Ilyushya** [comment]
### My `pubspec.yaml`:
```yaml
name: youtube_downloader_flutter
description: Downloads videos from youtube with ease!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0' #<3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  youtube_explode_dart: ^1.10.6
  stream_transform: ^2.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.7
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  win32: ^2.2.8
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0
  json_annotation: ^4.0.1
  url_launcher: ^6.0.9
  intl: ^0.17.0
  flutter_ffmpeg: ^0.4.2
  permission_handler: ^8.1.4+2
  open_file: ^3.2.1
  file_picker: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^4.1.1
  flutter_lints: ^1.0.0

dependency_overrides:
  freezed_annotation: 0.14.2


flutter:
  uses-material-design: true
  generate: true

```
